name: 'Run LanguageTool with reviewdog'
description: '🐶 Run LanguageTool with reviewdog on pull requests to improve code review experience.'
author: 'haya14busa'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  ### Flags for reviewdog ###
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-pr-review].'
    default: 'github-pr-check'
  ### Flags for LanguageTool ###
  # Ref: https://languagetool.org/http-api/swagger-ui/#!/default/post_check
  language:
    description: 'language of LanguageTool'
    default: 'en-US'
  enabled_rules:
    description: 'comma separeted enabledRules of LanguageTool'
  disabled_rules:
    description: 'comma separeted disabledRules of LanguageTool'
    default: 'WHITESPACE_RULE,EN_QUOTES,DASH_RULE,WORD_CONTAINS_UNDERSCORE,UPPERCASE_SENTENCE_START,ARROWS,COMMA_PARENTHESIS_WHITESPACE'
  enabled_categories:
    description: 'comma separeted enabledCategories of LanguageTool'
  disabled_categories:
    description: 'comma separeted disabledCategories of LanguageTool'
    default: 'TYPOS'
  enabled_only:
    description: 'enabledOnly of LanguageTool'
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'

# Ref: https://haya14busa.github.io/github-action-brandings/
# TODO: update branding if you want.
branding:
  icon: 'check'
  color: 'blue'
