name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test-check:
    name: runner / <linter-name> (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: info

  test-pr-check:
    if: github.event_name == 'pull_request'
    name: runner / <linter-name> (github-pr-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          level: info
          patterns: |
            README.md
          custom_api_endpoint: https://api.languagetoolplus.com

  test-pr-review:
    if: github.event_name == 'pull_request'
    name: runner / <linter-name> (github-pr-review)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: info
          patterns: |
            **/*.md
            !README.md
          custom_api_endpoint: https://api.languagetool.org
